name: Deploy Website

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.1


      - name: Install Dependencies
        run: bun install --production


      - name: Run Build Script
        run: bun run build

      - name: Configure Git
        run: |
          git config --global user.name "WiLuX-Source"
          git config --global user.email "61833703+WiLuX-Source@users.noreply.github.com"

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          bun run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}